[package]
name = "pgx-parent"
version = "0.1.0"

[workspace]
members = [
    ".",
    "pgx",
    "pgx-macros",
    "pgx-tests",
    "cargo-pgx",
]

[features]
default = ["pg11"]
pg10 = ["pgx/pg10", "pgx-tests/pg10"]
pg11 = ["pgx/pg11", "pgx-tests/pg11"]
pg12 = ["pgx/pg12", "pgx-tests/pg12"]

[dependencies]
pgx = { path = "pgx", default-features = false }
pgx-macros = { path = "pgx-macros" }
pgx-tests = { path = "pgx-tests", default-features = false }
