[package]
name = "cargo-pgx"
version = "0.1.0"
authors = ["Eric B. Ridge <eebbrr@gmail.com>"]
edition = "2018"
description = "Cargo Postgres extension manager"

[dependencies]
clap = {version = "2.33.0", features = ["yaml"]}
syn = { version = "1.0.5", features = ["extra-traits", "full", "fold", "parsing"] }
quote = "1.0.2"
proc-macro2 = { version = "1.0.6", features = ["span-locations"] }
rayon = "1.3.0"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = true
codegen-units = 1