[package]
name = "pgx-tests"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pgx = { path = "../pgx", default-features = false }
pgx-macros = { path = "../pgx-macros" }
lazy_static = "1.4.0"
shutdown_hooks = "0.1.0"
colored = "1.9.1"
libc = "0.2.66"
postgres = "0.17.0"
regex = "1.3.1"
