name: build

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  build:

    #runs-on: ${{ matrix.os }}
    runs-on: self-hosted

    strategy:
      matrix:
        version: [10, 11, 12]

    steps:
    - uses: actions/checkout@v1

    # Ubuntu system dependencies required to build Postgres from sources
    - name: install postgres build dependencies
      run: sudo apt install -y bison flex zlib1g zlib1g-dev

    # test our code
    - name: install cargo pgx on ${{ runner.name }}
      run: cd cargo-pgx && cargo install --path . --force
    - name: cargo test
      run: RUST_BACKTRACE=1 cargo test --target-dir /tmp/pgx-build/rust --all --features pg${{ matrix.version }} --no-default-features
