name: build

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  build:

    name: build pg-rs-bridge
    runs-on: [${{ matrix.os }}]

    strategy:
      matrix:
          os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: cargo build -vv
      run: cargo build -vv
