name: build

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [10, 11, 12]

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: install postgres build dependencies
      run: if [ "${{ matrix.os}}" == "ubuntu-latest" ] ; then sudo apt install libreadline6-dev bison flex; fi
    - name: postgres git/configure/make cache
      uses: actions/cache@v1
      with:
        path: target/REL_${{ matrix.version }}_STABLE
        key: ${{ runner.os }}-postgres-${{ matrix.version }}-v1
    - name: cargo build -vv
      run: cd pg-bridge && cargo build --no-default-features --features pg${{ matrix.version }} && pwd && find ${GITHUB_WORKSPACE} -type d
