name: build

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [10, 11, 12]

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: install postgres build dependencies
      run: if [ "${{ matrix.os}}" == "ubuntu-latest" ] ; then sudo apt install libreadline6-dev bison flex; fi

    # create caches for each of ~/.cargo, PG 10, 11, 12
    # we hardcode these rather than using ${{ matrix.feature }} because no matter what feature we're building for
    # build.rs needs all of these
    - name: cargo cache
      uses: actions/cache@v1
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-v1
    - name: postgres 10 git/configure/make cache
      uses: actions/cache@v1
      with:
        path: target/REL_10_STABLE
        key: ${{ runner.os }}-postgres-REL_10_STABLE-v1
    - name: postgres 11 git/configure/make cache
      uses: actions/cache@v1
      with:
        path: target/REL_11_STABLE
        key: ${{ runner.os }}-postgres-REL_11_STABLE-v1
    - name: postgres 12 git/configure/make cache
      uses: actions/cache@v1
      with:
        path: target/REL_12_STABLE
        key: ${{ runner.os }}-postgres-REL_12_STABLE-v1

    # build our code
    - name: cargo build
      run: cd pg-bridge && cargo build --no-default-features --features pg${{ matrix.version }}
