name: test

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  test:

    #runs-on: ${{ matrix.os }}
    runs-on: self-hosted

    strategy:
      matrix:
        version: [10, 11, 12]

    steps:
    - uses: actions/checkout@v1

    # which host are we running on?
    - name: hostname
      run: hostname

    # Ubuntu system dependencies required to build Postgres from sources
    - name: install postgres build dependencies
      run: sudo apt install -y bison flex zlib1g zlib1g-dev

    # install our cargo subcomment
    - name: install cargo pgx
      run: cd cargo-pgx && cargo install --path . --force

    # test our code
    - name: cargo test
      run: RUST_BACKTRACE=1 cargo test --target-dir /tmp/pgx-build-v${{ matrix.version }}/rust --all --features pg${{ matrix.version }} --no-default-features
